### ISSUE TITLE
No module named...

### ISSUE THREAD

**Issue by hrdwre** [Fluigent/fgt-SDK#78]
I have installed python SDK with the way described in manual but it still does not recognizing the modules. Please check the screenshot and errors given below..

![fluigent_sdk_problem_1](https://github.com/Fluigent/fgt-SDK/assets/122038247/39b0611b-3ebf-47c5-ab80-671fed9fbb07)

Traceback (most recent call last):
  File "c:\Users\...BasicSetValvePosition.py", line 16, in <module>
    from Fluigent.SDK import fgt_init, fgt_close
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\Fluigent\SDK\__init__.py", line 5, in <module>
    from . import low_level
  File "C:\Users\...\AppData\Local\Programs\Python\Python312\Lib\site-packages\Fluigent\SDK\low_level.py", line 10, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by Ygor-Oliveira** [comment]
Hello,

It seems that the `pkg_resources` module is deprecated and is no longer available by default in Python 3.12. To install it manually, please run the following command:

```
pip3.12.exe install setuptools
```

We are going to update the SDK code to account for this deprecation in the next release. Sorry for the inconvenience.

Best regards,
Ygor

**Comment by hrdwre** [comment]
Thanks for your fast reply.
________________________________
